name: Auto Create PR for Haiku Generator Branches

on:
  push:
    branches:
      - '**'  # Match all branches

jobs:
  create-pull-request:
    if: startsWith(github.ref, 'refs/heads/auto_haiku_generate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create Pull Request
        run: |
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
          # Authenticate GitHub CLI using the GITHUB_TOKEN
          echo "${{ github.token }}" | gh auth login --with-token
          
          # Extract branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head $BRANCH_NAME --json number | grep -c '"number"' || true)
          
          if [ "$PR_EXISTS" -eq "0" ]; then
            # Create a PR with descriptive title and body
            gh pr create \
              --base test-master \
              --head $BRANCH_NAME \
              --title "Auto-generated Haiku Updates from $BRANCH_NAME" \
              --body "This PR was automatically created from the $BRANCH_NAME branch.
              
              It contains updates to the following files:
              - haikus.csv
              - haiku_themes.txt
              - index.html
              
              This PR will be automatically merged if it meets all requirements."
              
            echo "Pull request created successfully."
          else
            echo "Pull request already exists for branch $BRANCH_NAME."
          fi
